"""Signal A — LLM classification via Groq (llama-3.3-70b-versatile).

Asks the model to judge *holistically* whether the text reads as human or AI-generated
and return a structured probability. This is the semantic counterpart to the structural
stylometry signal.

Graceful degradation: if no GROQ_API_KEY is configured or the API call fails, the
function returns ``available=False`` and the scoring layer falls back to stylometry
alone (shrinking the result toward 0.5). The service never crashes on a missing key.
"""
from __future__ import annotations

import json
import os
from typing import Dict

MODEL = "llama-3.3-70b-versatile"

_SYSTEM_PROMPT = (
    "You are a forensic text-attribution analyst. You judge whether a passage of text "
    "was written by a human or generated by an AI language model. Consider semantic "
    "coherence, register, voice, hedging, repetitiveness, and the 'too-even' polish "
    "typical of AI output. You are calibrated and honest about uncertainty: short or "
    "ambiguous text should land near 0.5, not at an extreme."
)

_USER_TEMPLATE = (
    "Assess the following text. Respond with ONLY a JSON object of the form "
    '{{"ai_probability": <number between 0 and 1>, "reasoning": "<one or two '
    'sentences>"}}. ai_probability is your estimate that the text is AI-generated '
    "(1.0 = certainly AI, 0.0 = certainly human, 0.5 = genuinely unsure).\n\n"
    "TEXT:\n\"\"\"\n{text}\n\"\"\""
)


def _clamp(x: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, x))


def llm_signal(text: str) -> Dict[str, object]:
    """Return {available, ai_probability, reasoning} for the given text."""
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        return {
            "available": False,
            "ai_probability": None,
            "reasoning": "GROQ_API_KEY not configured; LLM signal unavailable.",
        }

    try:
        from groq import Groq

        client = Groq(api_key=api_key)
        resp = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": _USER_TEMPLATE.format(text=text)},
            ],
            temperature=0.0,
            response_format={"type": "json_object"},
            max_tokens=300,
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        prob = _clamp(float(data.get("ai_probability", 0.5)))
        reasoning = str(data.get("reasoning", "")).strip() or "(no reasoning returned)"
        return {
            "available": True,
            "ai_probability": round(prob, 4),
            "reasoning": reasoning,
        }
    except Exception as exc:  # noqa: BLE001 — degrade gracefully on any API/parse error
        return {
            "available": False,
            "ai_probability": None,
            "reasoning": f"LLM signal error, falling back to stylometry: {exc}",
        }
